### ISSUE TITLE
Does not appear to work with struct.pack_into

### ISSUE THREAD

**Issue by alexforencich** [TexZK/bytesparse#1]
It seems that there is at least one case where this object doesn't currently work as a drop-in replacement for `bytearray`, specifically it doesn't seem to work with `struct.pack_into`:

    In [1]: import bytesparse, struct
    
    In [2]: b = bytesparse.Memory()
    
    In [3]: struct.pack_into("L", b, 0, 1234)
    ---------------------------------------------------------------------------
    TypeError                                 Traceback (most recent call last)
    <ipython-input-3-e2799cee4d47> in <module>
    ----> 1 struct.pack_into("L", b, 0, 1234)
    
    TypeError: argument must be read-write bytes-like object, not bytesparse._c.Memory

Is this just a limitation of the Python internal API?

**Comment by TexZK** [comment]
Yes, `bytesparse` cannot be a full replacement of `bytearray` because the latter can be managed directly as a memory chunk, while `bytesparse` works with Python objects.

As a workaround, you can use proper `bytesparse` methods to achieve the same goal:
```py
b.write(0, struct.pack("L", 1234))
```

**Comment by alexforencich** [comment]
TBH, I would not call it a workaround when you're suggesting that I do exactly what I am trying to avoid doing (find every place that touches the object in an incompatible way and rewrite it, across several dependencies).  It would probably be a good idea to have a disclaimer or something about all of the ways that bytesparse is not a drop-in replacement for bytes/bytearray/mmap/etc.  Sounds like this is not so much a limitation of bytesparse itself, instead it's more of a limitation in python's internal API for interfacing with bytes-like objects.
