### ISSUE TITLE
Document "generator" behavior of Memory.blocks()

### ISSUE THREAD

**Issue by Code7R** [TexZK/bytesparse#18]
Hi, as a convert from .NET world (Linq generic extendsion methods FTW!!) to the Python world, I hate the different behavior of iterators and generators, especially where in Python world the "generator" is usually considered to be runable only once (which is a shitty paradigm but we are in Python universe anyway...).

So, my wish is: please document the behavior of Memory.blocks() -> i.e. that it's runable only once, and if the user wants to keep the data, catching it into list() would be advisable.

**Comment by TexZK** [comment]
Ok, that's the inferred behavior of Python stuff, but I agree that good docs should be more explicit sometimes.

**Comment by TexZK** [comment]
I'm leaving this as *not planned* because the behavior of generators is very Python specific.
