### ISSUE TITLE
Memory.shift() losing blocks

### ISSUE THREAD

**Issue by Code7R** [TexZK/bytesparse#19]
MVE:

```
>>> foo = bytesparse.Memory.from_blocks([[123, b'foo']])
>>> area = foo.extract(100, 200, pattern=None)
>>> print(list(area.blocks()))
[[123, bytearray(b'foo')]]
>>> area.shift(300)
>>> print(list(area.blocks()))
[]
```

Expected behavior: the modified `area` object should report the block at position 423.

**Comment by TexZK** [comment]
Hi, please try by [providing `bound=False` to `extract()`](https://bytesparse.readthedocs.io/en/latest/_autosummary/bytesparse.inplace.Memory.html#bytesparse.inplace.Memory.extract).

By default, `bound=True` because it's the only way to hold information about any empty space around the selection bounds.

**Comment by Code7R** [comment]
Hi, okay, setting `bound=True` seems to resolve it. I.e. the selected data appears after shift(), with the correct offset.

But from the naive user's perspective this looks quite unnatural and surprising. So there is a semi-hidden concept of "bounds" in the Memory class which I probably haven't fully understood yet, and then there are hidden trimming attributes applied to content at some later moment (that is what shift... modifies, right?). But when you are programming defensively, and checking of what your object probably carries, the check with .blocks() or similar lures you into wrong assumptions. Please don't get me wrong, it probably makes sense in the overall picture, it's just sometimes hard to comprehend.

**Comment by TexZK** [comment]
I agree that there are some features that need better documentation and cross-referencing.

**Comment by Code7R** [comment]
I have done more with it now and sorry, no, it is still doing the wrong things. And it is just not about the bounds=... parameter. What I see is that when cut or extract is used, the data is simply reported as missing. .content_size tells the size, but the blocks() iterable is suddenly empty. And the similar pattern happens on other places.

Just have a look at the attached example, code should be self-explaining. Instead of getting the binary chunk being pasted multiple times into the Memory object, it seems to simply have destroyed its contents. For a moment, I though that the write() command might be intentionally consuming the contents, but even using a copy does not confirm that hypothesis. Or is maybe even .copy() buggy?

So the the output is:

> 
>   ID    SIZE  RANGE
> ----  ------  ----------------------
>    0      89  0x00000000--0x00000059
> ID    SIZE    RANGE
> ----  ------  -------
>   ID    SIZE  RANGE
> ----  ------  ----------------------
>    0      89  0x00000000--0x00000059
> ID    SIZE    RANGE
> ----  ------  -------
>   ID    SIZE  RANGE
> ----  ------  ----------------------
>    0      89  0x00000000--0x00000059
>   ID    SIZE  RANGE
> ----  ------  ----------------------
>    0      89  0x00000000--0x00000059
>    1      89  0x00000400--0x00000459
>    2      89  0x00000800--0x00000859
>   ID    SIZE  RANGE
> ----  ------  ----------------------
>    0      89  0x00000000--0x00000059
>   ID    SIZE  RANGE
> ----  ------  ----------------------
>    0      89  0x00000000--0x00000059
>    1      89  0x00000400--0x00000459
>    2      89  0x00000800--0x00000859
> python-BaseException
> Traceback (most recent call last):
>   File "/home/theone/.local/lib/python3.11/site-packages/hexrec/records.py", line 1835, in save_memory
>     cls.write_memory(stream, memory,
>   File "/home/theone/.local/lib/python3.11/site-packages/hexrec/records.py", line 1760, in write_memory
>     cls.write_blocks(stream, memory.blocks,
>   File "/home/theone/.local/lib/python3.11/site-packages/hexrec/records.py", line 1601, in write_blocks
>     records = blocks_to_records(blocks, cls,
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/theone/.local/lib/python3.11/site-packages/hexrec/records.py", line 251, in blocks_to_records
>     for start, items in blocks:
> TypeError: 'method' object is not iterable
> 
> Process finished with exit code 1

That is on Linux with Python 3.11.1. On Windows and with Python 3.9.x I have seen other things, like .cut() apparently has erased contents but not really, just replaced them with blanks (filling zeroes), but writing the extracted object back with write() has apparently not added anything.

And the commented out part shows the strange effects mentioned in the beginning.

And in the end I have ended up pasting the bytes() ranging manually. That seemed to work on the first glance, but then I cannot even save the resulting object to a file, see exception.


[playground.py.txt](https://github.com/TexZK/bytesparse/files/10474839/playground.py.txt)

**Comment by TexZK** [comment]
Ok I'm going to debug as soon as I can (I'm very busy these weeks).

**Comment by TexZK** [comment]
Hi, I've just debugged the code.
It looks like the problem is related to `Memory.copy()`, because currently it creates a **shallow** copy, as stated in its docstring.
So, for usability purposes, that method should create a **deep copy** instead.

As a workaround, please call `Memory,__deepcopy__()`.

As an example, I replaced the `red` file with `bytes.bin`, and uncommented the final part.
With this quick and dirty replacement, I get the following output:

```text
  ID    SIZE  RANGE
----  ------  ----------------------
   0     256  0x00000000--0x00000100

  ID    SIZE  RANGE
----  ------  ----------------------
   0     256  0x00000000--0x00000100
   1     256  0x00000400--0x00000500
   2     256  0x00000C00--0x00000D00

  ID    SIZE  RANGE
----  ------  ----------------------
   0     256  0x00000000--0x00000100

  ID    SIZE  RANGE
----  ------  ----------------------
   0     256  0x00000000--0x00000100
   1     256  0x00000400--0x00000500
   2     256  0x00000C00--0x00000D00

  ID    SIZE  RANGE
----  ------  ----------------------
   0     256  0x00000000--0x00000100

  ID    SIZE  RANGE
----  ------  ----------------------
   0     256  0x00000000--0x00000100
   1     256  0x00000400--0x00000500
   2     256  0x00000800--0x00000900

  ID    SIZE  RANGE
----  ------  ----------------------
   0     256  0x00000000--0x00000100

  ID    SIZE  RANGE
----  ------  ----------------------
   0     256  0x00000000--0x00000100
   1     256  0x00000400--0x00000500
   2     256  0x00000800--0x00000900

ID    SIZE    RANGE
----  ------  -------

ID    SIZE    RANGE
----  ------  -------

  ID    SIZE  RANGE
----  ------  ----------------------
   0     256  0x00000000--0x00000100
   1     256  0x00000400--0x00000500
   2     256  0x00000800--0x00000900
```

**Comment by TexZK** [comment]
About the exception: it looks like you're using a `hexrec` version take from *PyPI*, which isn't aligned with the `bytesparse` package. You should instead install both from source.
